### ISSUE TITLE
Any timeline release of the official course extensions?

### ISSUE THREAD

**Issue by MichaelBagnasco** [nestjs/courses.nestjs.com#47]
I really enjoyed the official course and I'd like to know when the course extensions will be available.

**Comment by kamilmysliwiec** [comment]
We’re working on a bunch now and we’re slowly wrapping up the first two: GraphQL code-first & GraphQL schema-first (we're in a video recording phase now). Afterward Authentication, microservices, advanced Nest, and many other niche in-depth topics (in no particular order), hopefully, as soon as possible.
