### ISSUE TITLE
Release date for Nestjs course extensions

### ISSUE THREAD

**Issue by FranciscoKloganB** [nestjs/courses.nestjs.com#52]
Hello fellow devs,

Do we have a estimate for the release date of `Authorization and Authentication` and `Microservices` course extensions? What about the other two?

**Comment by kamilmysliwiec** [comment]
Hey @FranciscoKloganB,
We're actively working on the new course extensions and once we have most materials ready, we'll start pre-order, similarly to what have done with the fundamentals course. To not miss it, subscribe to our newsletter!
