### ISSUE TITLE
Public URL for certificate of completion

### ISSUE THREAD

**Issue by FranciscoKloganB** [nestjs/courses.nestjs.com#53]
Hello again,

Just finished the fundamentals course (thanks for the content by the way).

I just got access to the certificate of completion and there is a certificate ID, however, I do not seem to find the Certificate Public URL, for example, to share it on LinkedIn certificate areas.

Did not find anything on your website, nor Teachable FAQs.

Do we support this feature?

**Comment by kamilmysliwiec** [comment]
Unfortunately, this isn't something that we support atm. I'd suggest reaching out to Teachable asking if they have such a feature in the backlog.
