### ISSUE TITLE
Payment: the card was declined

### ISSUE THREAD

**Issue by draylegend** [nestjs/courses.nestjs.com#64]
I'm trying to buy [this course](https://sso.teachable.com/secure/325803/checkout/4213276/authentication-and-authorization), but getting the error `The card was declined`.

How can I pay with paypal? Coz I already bought with paypal, but then it was removed :(((

Or add at least `klarna`

**Comment by kamilmysliwiec** [comment]
Please, email us at hello@trilon.io
