### ISSUE TITLE
Request for Inclusion of Nest.js Course in GitHub Student Developer Pack

### ISSUE THREAD

**Issue by quizfactorynl** [nestjs/courses.nestjs.com#80]
> The GitHub Student Developer Pack is a program offered by GitHub that provides students with free access to a variety of developer tools, services and course. This pack is designed to help students learn about software development and gain practical experience using the same tools that professional developers use.

@valorkin could you consider adding this course to the GitHub Student Developer Pack? As a student eager to learn Nest.js, the course fees are prohibitively high for me. Offering a discount would not only benefit students like me but also promote your content, similar to what other organizations like `Frontend Masters`, `AlgoExpert`, `Educative` and others are doing.

**Comment by kamilmysliwiec** [comment]
There are no plans for this atm.
