### ISSUE TITLE
License inquiry

### ISSUE THREAD

**Issue by AthenaOdin** [nestjs/courses.nestjs.com#81]
I saw the same NestJS course available on a Chinese platform (XYZ). They offer it for free in 360p resolution and in HD with a subscription. Do they have a partnership with you or any official license permitted by NestJS?

**Comment by micalevisk** [comment]
which platform is this?

**Comment by AthenaOdin** [comment]
@micalevisk bili

**Comment by kamilmysliwiec** [comment]
These courses are stolen and illegally distributed in China.
