### ISSUE TITLE
NestJS Architecture and Advanced Patterns course code outdated to newest mongodb

### ISSUE THREAD

**Issue by conrado** [nestjs/courses.nestjs.com#86]
Hi there,

while following the course, right on this page: https://learn.nestjs.com/courses/architecture-and-advanced-patterns/lectures/49542779

I noticed what seems to be that the course code no longer seems to work with the newest mongodb library, type conflicts are present on line 30 of `src/shared/infrastructure/event-store/events-bridge.ts`:

```
Type 'ChangeStream<any, any>' is missing the following properties from type 'ChangeStream<Document, ChangeStreamDocument<Document>>': contextOwner, _resume
```

I would provide a reproducible repo, but I'm uncertain you would like the code published.

I tried reverting to @nestjs/cli so I could cherry-pick all my commits, but it seem that schematics are broken when trying to run with such an nestjs and cli version.

**Comment by kamilmysliwiec** [comment]
Thanks for reporting! We'll look into that shortly

**Comment by kamilmysliwiec** [comment]
Found a root cause https://github.com/Automattic/mongoose/issues/14731
